import { CloudService } from "./gcp-services";

export const awsCategories = [
  "Compute",
  "Containers",
  "Serverless",
  "Storage",
  "Databases",
  "Networking",
  "Content Delivery",
  "Security & Identity",
  "Monitoring & Governance",
  "DevOps",
  "Messaging & Integration",
  "Analytics",
  "AI / ML",
  "Management & Cost",
  "Support",
];

export const awsServices: CloudService[] = [
  // ────────── Compute ──────────
  {
    id: "ec2",
    name: "EC2",
    shortName: "Elastic Compute Cloud",
    category: "Compute",
    code: "EC2",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Virtual servers in the cloud. IaaS compute.",
    useCases: ["Web / app servers", "Any workload needing full OS control"],
    keyFeatures: [
      "Instance families: General (t/m), Compute (c), Memory (r/x), Storage (d/i), GPU (p/g)",
      "Purchase options: On-Demand, Reserved, Savings Plans, Spot, Dedicated Hosts",
    ],
    examTips: [
      "On-Demand = pay as you go. Reserved = 1/3-yr commitment, up to 72% off.",
      "Spot = up to 90% off, can be terminated with 2-min notice → fault-tolerant workloads.",
      "Dedicated Host for licensing bound to physical server (e.g. Windows Server BYOL).",
      "Savings Plans are more flexible than Reserved Instances.",
    ],
  },
  {
    id: "lightsail",
    name: "Lightsail",
    category: "Compute",
    code: "LS",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Simple virtual private server with bundled compute, storage, and transfer.",
    useCases: ["Small websites", "Simple blogs / dev-test"],
    keyFeatures: ["Fixed monthly price"],
    examTips: ["Lightsail = 'easy button' for small workloads. Very affordable, flat price."],
  },
  {
    id: "batch",
    name: "AWS Batch",
    category: "Compute",
    code: "BA",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Fully managed batch computing at any scale.",
    useCases: ["Massive batch jobs, genomics, financial modeling"],
    keyFeatures: ["Job queues, compute environments", "Integrates with Spot"],
    examTips: ["High-volume batch jobs → AWS Batch (not EMR)."],
  },
  {
    id: "beanstalk",
    name: "Elastic Beanstalk",
    shortName: "EB",
    category: "Compute",
    code: "EB",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "PaaS — deploy apps, AWS provisions EC2, ELB, Auto Scaling automatically.",
    useCases: ["Upload code and let AWS manage infrastructure", "Quick web deployments"],
    keyFeatures: ["Supports Java, .NET, PHP, Node, Python, Ruby, Go, Docker"],
    examTips: [
      "PaaS — you still own the infra (unlike Lambda), but AWS configures it for you.",
      "Best for developers who want to focus on code, not infra.",
    ],
  },

  // ────────── Containers ──────────
  {
    id: "ecs",
    name: "ECS",
    shortName: "Elastic Container Service",
    category: "Containers",
    code: "ECS",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "AWS-native container orchestration. Runs on EC2 or Fargate.",
    useCases: ["Containerized apps", "Simpler alternative to Kubernetes"],
    keyFeatures: ["Task definitions", "Launch types: EC2 or Fargate"],
    examTips: ["ECS + Fargate = serverless containers, no EC2 management."],
  },
  {
    id: "eks",
    name: "EKS",
    shortName: "Elastic Kubernetes Service",
    category: "Containers",
    code: "EKS",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Managed Kubernetes clusters.",
    useCases: ["Kubernetes workloads", "Hybrid/multi-cloud"],
    keyFeatures: ["Runs on EC2 or Fargate", "Upstream Kubernetes"],
    examTips: ["Kubernetes-first → EKS. For simpler AWS-native containers → ECS."],
  },
  {
    id: "fargate",
    name: "Fargate",
    category: "Containers",
    code: "FG",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Serverless compute engine for containers (ECS + EKS).",
    useCases: ["Run containers without managing EC2"],
    keyFeatures: ["Per-second billing", "No node management"],
    examTips: ["'No servers to manage + containers' → Fargate."],
  },
  {
    id: "ecr",
    name: "ECR",
    shortName: "Elastic Container Registry",
    category: "Containers",
    code: "ECR",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Managed Docker / OCI image registry.",
    useCases: ["Store container images"],
    keyFeatures: ["Private by default", "Vulnerability scanning"],
    examTips: ["ECR is private; ECR Public exists for public images."],
  },

  // ────────── Serverless ──────────
  {
    id: "lambda",
    name: "Lambda",
    category: "Serverless",
    code: "λ",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Run code without provisioning servers. Pay per 1 ms of execution.",
    useCases: ["API backends", "Event-driven glue", "Data processing"],
    keyFeatures: [
      "Up to 15 min execution time",
      "10 GB memory, 10 GB ephemeral storage",
      "Invoked by API GW, S3, DynamoDB streams, EventBridge, SQS",
    ],
    examTips: [
      "Max duration = 15 min. Longer workloads → Step Functions / Fargate / EC2.",
      "Concurrent execution limit per account per region (default 1000).",
      "Cold start mitigated by Provisioned Concurrency.",
    ],
  },
  {
    id: "api-gateway",
    name: "API Gateway",
    shortName: "APIGW",
    category: "Serverless",
    code: "API",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Managed REST, HTTP, WebSocket API front-door.",
    useCases: ["Serverless REST APIs", "WebSocket APIs"],
    keyFeatures: ["Throttling, caching", "Authz (IAM / Cognito / Lambda authorizer)"],
    examTips: ["API Gateway + Lambda = classic serverless architecture."],
  },
  {
    id: "step-functions",
    name: "Step Functions",
    shortName: "SFN",
    category: "Serverless",
    code: "SFN",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Visual workflow orchestrator for AWS services.",
    useCases: ["Long-running workflows", "Error handling across Lambdas"],
    keyFeatures: ["Standard (up to 1 yr) and Express (5 min) workflows"],
    examTips: ["Multiple Lambda functions need to chain with retries → Step Functions."],
  },

  // ────────── Storage ──────────
  {
    id: "s3",
    name: "S3",
    shortName: "Simple Storage Service",
    category: "Storage",
    code: "S3",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Object storage. 99.999999999% (11 9s) durability.",
    useCases: ["Static sites", "Data lakes", "Backups", "Media storage"],
    keyFeatures: [
      "Classes: Standard, Intelligent-Tiering, Standard-IA, One Zone-IA, Glacier Instant/Flexible/Deep Archive",
      "Versioning, MFA Delete, Object Lock, Replication (CRR/SRR)",
      "Server-side encryption: SSE-S3, SSE-KMS, SSE-C",
    ],
    examTips: [
      "Glacier = archive, retrieval minutes-to-hours. Deep Archive = 12h+ retrieval, cheapest.",
      "Intelligent-Tiering = automatic class changes when access patterns unknown.",
      "S3 is REGIONAL (buckets live in a region); names are GLOBALLY unique.",
      "Block Public Access is on by default — unblock consciously.",
    ],
  },
  {
    id: "ebs",
    name: "EBS",
    shortName: "Elastic Block Store",
    category: "Storage",
    code: "EBS",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Block storage volumes for EC2 (AZ-bound).",
    useCases: ["EC2 boot/data volumes", "DB storage on EC2"],
    keyFeatures: ["gp3 / io2 (SSD), st1 / sc1 (HDD)", "Snapshots to S3", "Encryption by default"],
    examTips: [
      "EBS = one AZ. To attach to a different AZ → snapshot → restore in new AZ.",
      "Snapshots are incremental, stored in S3 (but not visible in S3 UI).",
      "io2 Block Express = highest IOPS, for mission-critical DBs.",
    ],
  },
  {
    id: "efs",
    name: "EFS",
    shortName: "Elastic File System",
    category: "Storage",
    code: "EFS",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Managed NFS, shared across multiple EC2 instances and AZs.",
    useCases: ["Shared files across EC2s", "Containers needing POSIX FS"],
    keyFeatures: ["Regional (multi-AZ)", "Linux-only (NFSv4)"],
    examTips: [
      "NFS / shared between multiple EC2 → EFS.",
      "EFS = Linux. For Windows SMB → FSx for Windows.",
    ],
  },
  {
    id: "fsx",
    name: "FSx",
    category: "Storage",
    code: "FSX",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Managed third-party file systems: Windows, Lustre, NetApp ONTAP, OpenZFS.",
    useCases: ["Windows SMB shares", "HPC / Lustre"],
    keyFeatures: ["FSx for Windows = SMB", "FSx for Lustre = HPC"],
    examTips: [
      "Windows file shares → FSx for Windows.",
      "High-performance compute (HPC, ML training) → FSx for Lustre.",
    ],
  },
  {
    id: "storage-gateway",
    name: "Storage Gateway",
    category: "Storage",
    code: "SGW",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Hybrid cloud storage bridge between on-prem and AWS.",
    useCases: ["Extend on-prem storage to AWS", "Backup/archive to S3"],
    keyFeatures: ["File Gateway (NFS/SMB)", "Volume Gateway (iSCSI)", "Tape Gateway"],
    examTips: [
      "On-prem needs to access S3 via NFS/SMB → File Gateway.",
      "On-prem VTL replacement → Tape Gateway.",
    ],
  },
  {
    id: "snow-family",
    name: "Snow Family",
    category: "Storage",
    code: "SN",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Physical devices to transfer data in/out of AWS.",
    useCases: ["Petabyte-scale data migration", "Edge compute in disconnected locations"],
    keyFeatures: ["Snowcone (8 TB)", "Snowball Edge (80 TB)", "Snowmobile (100 PB truck)"],
    examTips: [
      "Too much data for the network → Snow.",
      "Disconnected / rugged environments → Snowcone / Snowball Edge.",
    ],
  },
  {
    id: "backup",
    name: "AWS Backup",
    category: "Storage",
    code: "BK",
    color: "#7AA116",
    bgColor: "#e6f4ea",
    description: "Centralized backup across EBS, RDS, DynamoDB, EFS, FSx, Storage Gateway.",
    useCases: ["Unified backup policies", "Compliance retention"],
    keyFeatures: ["Backup plans", "Vault Lock"],
    examTips: ["'Single place to manage backups across services' → AWS Backup."],
  },

  // ────────── Databases ──────────
  {
    id: "rds",
    name: "RDS",
    shortName: "Relational Database Service",
    category: "Databases",
    code: "RDS",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "Managed relational DBs: MySQL, PostgreSQL, MariaDB, Oracle, SQL Server.",
    useCases: ["Traditional relational apps"],
    keyFeatures: ["Multi-AZ (HA standby)", "Read replicas (up to 15)", "Automated backups"],
    examTips: [
      "Multi-AZ = HA/failover (sync standby, NOT readable).",
      "Read Replicas = scale reads (async, eventually consistent).",
      "Multi-AZ has an RPO near 0 because replication is synchronous.",
    ],
  },
  {
    id: "aurora",
    name: "Aurora",
    category: "Databases",
    code: "AU",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "AWS-cloud-native MySQL / PostgreSQL-compatible DB. 5x MySQL, 3x PostgreSQL perf.",
    useCases: ["High-performance relational workloads", "Serverless relational"],
    keyFeatures: ["6 copies of data across 3 AZs", "Aurora Serverless v2"],
    examTips: [
      "Aurora Serverless = on-demand relational for variable workloads.",
      "Up to 15 read replicas with sub-10 ms replication.",
      "Cheaper than Oracle / SQL Server → often the migration target from commercial DBs.",
    ],
  },
  {
    id: "dynamodb",
    name: "DynamoDB",
    category: "Databases",
    code: "DDB",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "Serverless NoSQL key-value + document DB. Single-digit ms performance.",
    useCases: ["Gaming leaderboards", "User profiles", "Session stores"],
    keyFeatures: [
      "On-Demand or Provisioned capacity",
      "Global Tables (multi-region active-active)",
      "DAX = in-memory cache",
      "TTL for auto-expiry, Streams for CDC",
    ],
    examTips: [
      "NoSQL + serverless + predictable low latency → DynamoDB.",
      "Global Tables for multi-region active-active.",
      "DAX = microsecond latency accelerator.",
    ],
  },
  {
    id: "elasticache",
    name: "ElastiCache",
    category: "Databases",
    code: "EC",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "Managed Redis and Memcached.",
    useCases: ["Caching", "Session store", "Real-time leaderboards"],
    keyFeatures: ["Redis has persistence + replication; Memcached is simpler + multi-threaded"],
    examTips: [
      "Redis = persistence, pub/sub, sorted sets.",
      "Memcached = simple cache, scales horizontally, NO persistence.",
    ],
  },
  {
    id: "redshift",
    name: "Redshift",
    category: "Databases",
    code: "RS",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "Petabyte-scale data warehouse. Columnar storage, massively parallel.",
    useCases: ["OLAP / analytics", "BI dashboards on historical data"],
    keyFeatures: ["Redshift Serverless", "Spectrum (query S3 without loading)"],
    examTips: [
      "OLAP / analytics / BI → Redshift.",
      "Spectrum = query S3 directly. Think federated analytics.",
      "Don't use for OLTP.",
    ],
  },
  {
    id: "documentdb",
    name: "DocumentDB",
    category: "Databases",
    code: "DOC",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "Managed MongoDB-compatible DB.",
    useCases: ["MongoDB migrations"],
    keyFeatures: ["MongoDB 4.0 / 5.0 API"],
    examTips: ["MongoDB workloads on AWS → DocumentDB."],
  },
  {
    id: "neptune",
    name: "Neptune",
    category: "Databases",
    code: "NEP",
    color: "#2E27AD",
    bgColor: "#e8f0fe",
    description: "Managed graph database (Gremlin, SPARQL, openCypher).",
    useCases: ["Social networks", "Fraud detection", "Recommendation engines"],
    keyFeatures: ["High availability across AZs"],
    examTips: ["Graph relationships / 'nodes and edges' → Neptune."],
  },

  // ────────── Networking ──────────
  {
    id: "vpc",
    name: "VPC",
    category: "Networking",
    code: "VPC",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Isolated virtual network in AWS. Region-scoped.",
    useCases: ["Network isolation", "Hybrid connectivity"],
    keyFeatures: [
      "Subnets (AZ-scoped), Route Tables, Internet Gateway, NAT Gateway",
      "Security Groups (stateful) vs NACLs (stateless)",
      "VPC Peering (non-transitive)",
    ],
    examTips: [
      "Subnets are AZ-bound. VPC is region-bound (unlike GCP VPC which is global).",
      "SG = stateful (return traffic auto-allowed). NACL = stateless (explicit rules each way).",
      "NAT Gateway = outbound from private subnet; Internet Gateway = inbound + outbound from public subnet.",
    ],
  },
  {
    id: "elb",
    name: "Elastic Load Balancing",
    shortName: "ELB",
    category: "Networking",
    code: "ELB",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Managed load balancers: ALB, NLB, GWLB, Classic LB (legacy).",
    useCases: ["Distribute traffic across EC2 / containers / Lambda"],
    keyFeatures: [
      "ALB (L7 HTTP/HTTPS) — path/host routing",
      "NLB (L4 TCP/UDP) — ultra-low latency, static IPs",
      "GWLB (L3 Gateway) — 3rd-party appliances",
    ],
    examTips: [
      "HTTP, path/host-based routing → ALB.",
      "TCP/UDP, static IP, millions of requests → NLB.",
      "Deploy firewalls / IDS inline → Gateway LB.",
    ],
  },
  {
    id: "route53",
    name: "Route 53",
    category: "Networking",
    code: "R53",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Authoritative DNS + domain registrar + health checks.",
    useCases: ["DNS for domains", "DNS failover", "Geo / latency routing"],
    keyFeatures: ["Routing policies: Simple, Weighted, Latency, Geo, Failover, Multi-Value"],
    examTips: [
      "Failover routing + health checks for DR.",
      "Latency-based routing = route to fastest region.",
      "Geolocation = where the user is. Geoproximity = bias toward a region.",
    ],
  },
  {
    id: "direct-connect",
    name: "Direct Connect",
    shortName: "DX",
    category: "Networking",
    code: "DX",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Dedicated private fiber from on-prem to AWS.",
    useCases: ["Low-latency, high-throughput hybrid", "Compliance forbidding public internet"],
    keyFeatures: ["1 / 10 / 100 Gbps", "Takes weeks to set up"],
    examTips: [
      "Consistent, private, high-throughput link → Direct Connect.",
      "For encrypted traffic → DX + VPN (or just Site-to-Site VPN).",
    ],
  },
  {
    id: "vpn",
    name: "Site-to-Site VPN",
    category: "Networking",
    code: "VPN",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "IPsec VPN over public internet to VPC.",
    useCases: ["Quick hybrid connectivity", "Low-bandwidth encrypted link"],
    keyFeatures: ["Min. config time (hours)", "Encrypted"],
    examTips: ["Need hybrid connectivity FAST → VPN. Need permanence + throughput → DX."],
  },
  {
    id: "transit-gateway",
    name: "Transit Gateway",
    shortName: "TGW",
    category: "Networking",
    code: "TGW",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Hub connecting thousands of VPCs and on-prem networks.",
    useCases: ["Replace complex VPC peering meshes"],
    keyFeatures: ["Transitive routing", "Cross-region peering"],
    examTips: [
      "Hundreds of VPCs to connect → Transit Gateway (not mesh peering).",
      "VPC Peering is NON-transitive; Transit Gateway IS transitive.",
    ],
  },
  {
    id: "global-accelerator",
    name: "Global Accelerator",
    shortName: "GA",
    category: "Networking",
    code: "GA",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Anycast static IPs routed through AWS backbone to regional endpoints.",
    useCases: ["Multi-region apps", "Gaming / VoIP latency-sensitive workloads"],
    keyFeatures: ["2 static IPs", "Health-based failover"],
    examTips: [
      "Global Accelerator = network layer (TCP/UDP, static IPs).",
      "CloudFront = content caching (HTTP).",
    ],
  },
  {
    id: "privatelink",
    name: "PrivateLink",
    category: "Networking",
    code: "PL",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Private connectivity to AWS services / SaaS via VPC endpoints.",
    useCases: ["Consume services without internet exposure"],
    keyFeatures: ["Interface endpoints (PrivateLink)", "Gateway endpoints (S3, DynamoDB)"],
    examTips: ["S3 / DynamoDB from a VPC without internet → Gateway Endpoint (free)."],
  },

  // ────────── Content Delivery ──────────
  {
    id: "cloudfront",
    name: "CloudFront",
    category: "Content Delivery",
    code: "CF",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Global CDN with 600+ edge locations.",
    useCases: ["Static site delivery", "Video streaming", "API acceleration"],
    keyFeatures: ["Edge caching", "Signed URLs/cookies", "Lambda@Edge"],
    examTips: [
      "Serve content globally with low latency → CloudFront.",
      "Origin can be S3, ALB, EC2, or any HTTP server.",
    ],
  },

  // ────────── Security & Identity ──────────
  {
    id: "iam",
    name: "IAM",
    category: "Security & Identity",
    code: "IAM",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Users, groups, roles, and policies controlling access to AWS.",
    useCases: ["User login", "Service-to-service access via Roles"],
    keyFeatures: ["Policies (JSON)", "Roles (assumed)", "MFA", "Access Keys"],
    examTips: [
      "Always attach Roles to EC2/Lambda — never hardcode keys.",
      "Enable MFA on root. Lock away root credentials.",
      "Use IAM Access Analyzer to find over-permissive grants.",
      "IAM is GLOBAL (no region).",
    ],
  },
  {
    id: "iam-identity-center",
    name: "IAM Identity Center",
    category: "Security & Identity",
    code: "SSO",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "SSO across AWS accounts (previously AWS SSO).",
    useCases: ["Centralized workforce sign-in for many accounts"],
    keyFeatures: ["Integrates with SAML/OIDC IdPs"],
    examTips: ["SSO across multiple AWS accounts → IAM Identity Center."],
  },
  {
    id: "cognito",
    name: "Cognito",
    category: "Security & Identity",
    code: "CG",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "User sign-up / sign-in for web and mobile apps.",
    useCases: ["App user directory", "Social + SAML federated login"],
    keyFeatures: ["User Pools (identity)", "Identity Pools (federation to AWS)"],
    examTips: ["App end-user authentication → Cognito (NOT IAM)."],
  },
  {
    id: "kms",
    name: "KMS",
    shortName: "Key Management Service",
    category: "Security & Identity",
    code: "KMS",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Managed symmetric/asymmetric keys for encryption.",
    useCases: ["Encrypt data at rest across AWS services"],
    keyFeatures: ["AWS-managed keys vs Customer-managed keys (CMK)", "Automatic yearly rotation"],
    examTips: [
      "SSE-KMS = envelope encryption using a KMS CMK.",
      "CMKs stay inside KMS — you can't export them.",
      "CloudHSM = dedicated HSM under YOUR control (single-tenant).",
    ],
  },
  {
    id: "secrets-manager",
    name: "Secrets Manager",
    category: "Security & Identity",
    code: "SEC",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Store and auto-rotate secrets (DB creds, API keys).",
    useCases: ["RDS credential rotation", "API key storage"],
    keyFeatures: ["Built-in RDS/Redshift/DocumentDB rotation"],
    examTips: [
      "Parameter Store is cheaper but no automatic rotation.",
      "Secrets Manager ≈ $0.40/secret/month — use for credentials needing rotation.",
    ],
  },
  {
    id: "waf",
    name: "WAF",
    shortName: "Web Application Firewall",
    category: "Security & Identity",
    code: "WAF",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Layer 7 firewall for CloudFront, ALB, API Gateway, AppSync.",
    useCases: ["Block SQLi, XSS, bots"],
    keyFeatures: ["Managed rule groups", "Rate-based rules"],
    examTips: ["Layer-7 threats → WAF. Layer 3/4 DDoS → Shield."],
  },
  {
    id: "shield",
    name: "Shield",
    category: "Security & Identity",
    code: "SH",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "DDoS protection — Standard (free) and Advanced ($3K/mo).",
    useCases: ["Layer 3/4 + app-layer DDoS protection"],
    keyFeatures: ["Shield Advanced = 24/7 DRT + cost protection"],
    examTips: [
      "Shield Standard auto-enabled on all accounts.",
      "Shield Advanced required for deep DDoS mitigation + WAF included.",
    ],
  },
  {
    id: "guardduty",
    name: "GuardDuty",
    category: "Security & Identity",
    code: "GD",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Intelligent threat detection using CloudTrail, VPC Flow, DNS logs.",
    useCases: ["Detect compromised credentials, crypto mining, unusual API calls"],
    keyFeatures: ["Always-on ML-based detection", "No agents"],
    examTips: ["Threat detection in AWS → GuardDuty."],
  },
  {
    id: "inspector",
    name: "Inspector",
    category: "Security & Identity",
    code: "INS",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Automated vulnerability scanning for EC2, ECR, Lambda.",
    useCases: ["CVE scanning for EC2 AMIs, container images, Lambda layers"],
    keyFeatures: ["Continuous scanning"],
    examTips: ["Scan for CVEs → Inspector."],
  },
  {
    id: "macie",
    name: "Macie",
    category: "Security & Identity",
    code: "MAC",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "ML-based discovery of sensitive data (PII) in S3.",
    useCases: ["Find PII / secrets in S3 buckets"],
    keyFeatures: ["Data classification jobs"],
    examTips: ["PII in S3 → Macie."],
  },
  {
    id: "security-hub",
    name: "Security Hub",
    category: "Security & Identity",
    code: "SHB",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Central view of security findings across AWS accounts + CIS/PCI benchmarks.",
    useCases: ["Single pane of glass for GuardDuty/Inspector/Macie"],
    keyFeatures: ["Aggregates findings"],
    examTips: ["Central security dashboard → Security Hub."],
  },
  {
    id: "acm",
    name: "Certificate Manager",
    shortName: "ACM",
    category: "Security & Identity",
    code: "ACM",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Provision and manage free TLS certificates.",
    useCases: ["TLS for ALB, CloudFront, API GW"],
    keyFeatures: ["Free public certs", "Auto-renewal"],
    examTips: ["Public TLS certs for AWS services → ACM (free)."],
  },

  // ────────── Monitoring & Governance ──────────
  {
    id: "cloudwatch",
    name: "CloudWatch",
    category: "Monitoring & Governance",
    code: "CW",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Metrics, logs, dashboards, and alarms.",
    useCases: ["Alarming on metrics", "Log centralization"],
    keyFeatures: [
      "Metrics (1-min or 1-sec high-res)",
      "Logs Insights for querying",
      "Alarms → SNS / Auto Scaling",
    ],
    examTips: [
      "CloudWatch Logs for application logs, metrics for numeric data.",
      "CloudWatch Alarms can trigger SNS topics or Auto Scaling actions.",
    ],
  },
  {
    id: "cloudtrail",
    name: "CloudTrail",
    category: "Monitoring & Governance",
    code: "CT",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "API audit log of every AWS action.",
    useCases: ["Compliance", "Forensic analysis", "Who deleted the bucket?"],
    keyFeatures: ["Management + Data events", "Delivered to S3"],
    examTips: [
      "CloudTrail = WHO did WHAT (API calls).",
      "CloudWatch = HOW resources behave (metrics / logs).",
      "Retained 90 days by default — send to S3 for longer retention.",
    ],
  },
  {
    id: "config",
    name: "AWS Config",
    category: "Monitoring & Governance",
    code: "CFG",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Record configuration state over time, evaluate compliance rules.",
    useCases: ["Compliance audits", "Config drift detection"],
    keyFeatures: ["Managed + custom rules", "Remediation actions"],
    examTips: [
      "Is my bucket public? Is MFA enabled? → AWS Config rules.",
      "Config tracks HISTORY of configuration changes.",
    ],
  },
  {
    id: "trusted-advisor",
    name: "Trusted Advisor",
    category: "Monitoring & Governance",
    code: "TA",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Best-practice checks: cost, performance, security, fault tolerance, limits.",
    useCases: ["Free ongoing AWS health check"],
    keyFeatures: ["Full checks require Business/Enterprise Support"],
    examTips: [
      "All checks available only with Business or Enterprise support plan.",
      "Categories: Cost, Performance, Security, Fault tolerance, Service Limits.",
    ],
  },
  {
    id: "personal-health",
    name: "Personal Health Dashboard",
    category: "Monitoring & Governance",
    code: "PHD",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Events affecting YOUR resources (now part of AWS Health).",
    useCases: ["Maintenance notifications"],
    keyFeatures: ["Per-account view"],
    examTips: ["Status Page = global. PHD / AWS Health = personalized."],
  },

  // ────────── DevOps ──────────
  {
    id: "cloudformation",
    name: "CloudFormation",
    shortName: "CFN",
    category: "DevOps",
    code: "CFN",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Infrastructure as Code using JSON/YAML templates.",
    useCases: ["Repeatable stacks", "Multi-region deployments"],
    keyFeatures: ["StackSets for multi-account/region", "Change Sets before apply"],
    examTips: ["AWS-native IaC → CloudFormation. Multi-cloud → Terraform."],
  },
  {
    id: "codepipeline",
    name: "CodePipeline",
    category: "DevOps",
    code: "CP",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "CI/CD orchestration — connects Source → Build → Test → Deploy.",
    useCases: ["Release pipelines"],
    keyFeatures: ["Integrates with CodeCommit/CodeBuild/CodeDeploy"],
    examTips: ["Full pipeline orchestration → CodePipeline."],
  },
  {
    id: "codebuild",
    name: "CodeBuild",
    category: "DevOps",
    code: "CB",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Managed build service — compiles, tests, produces artifacts.",
    useCases: ["Build step in a pipeline"],
    keyFeatures: ["Pay per build minute", "buildspec.yml"],
    examTips: ["CI build / test runner on AWS → CodeBuild."],
  },
  {
    id: "codedeploy",
    name: "CodeDeploy",
    category: "DevOps",
    code: "CD",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Automate deployments to EC2, Lambda, ECS, on-prem.",
    useCases: ["Blue/green or rolling deploys"],
    keyFeatures: ["In-place vs blue/green"],
    examTips: ["Deploys to EC2/on-prem/Lambda → CodeDeploy."],
  },
  {
    id: "xray",
    name: "X-Ray",
    category: "DevOps",
    code: "XR",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Distributed tracing for microservices.",
    useCases: ["Find latency bottlenecks", "Service map visualization"],
    keyFeatures: ["SDK for Lambda, ECS, EC2"],
    examTips: ["Latency across microservices / Lambdas → X-Ray."],
  },
  {
    id: "systems-manager",
    name: "Systems Manager",
    shortName: "SSM",
    category: "DevOps",
    code: "SSM",
    color: "#ED7100",
    bgColor: "#fff3e0",
    description: "Fleet management for EC2 and on-prem: patch, run-command, session, parameters.",
    useCases: ["Patch Manager", "Session Manager (SSH-less)", "Parameter Store"],
    keyFeatures: ["No bastion hosts with Session Manager", "Run Command"],
    examTips: [
      "Parameter Store (under SSM) is free for standard tier — good for non-secret configs.",
      "Session Manager replaces bastion hosts for secure shell access.",
    ],
  },

  // ────────── Messaging & Integration ──────────
  {
    id: "sqs",
    name: "SQS",
    shortName: "Simple Queue Service",
    category: "Messaging & Integration",
    code: "SQS",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Managed message queues. At-least-once delivery (Standard) or FIFO.",
    useCases: ["Decoupling services", "Work queues"],
    keyFeatures: ["Standard (unlimited TPS)", "FIFO (300 TPS)", "Visibility timeout", "DLQs"],
    examTips: [
      "Producer → Queue → Consumer (pull).",
      "FIFO = strict order + exactly-once.",
      "Standard = at-least-once, duplicates possible.",
    ],
  },
  {
    id: "sns",
    name: "SNS",
    shortName: "Simple Notification Service",
    category: "Messaging & Integration",
    code: "SNS",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Pub/Sub messaging. Topic → many subscribers (SQS, Lambda, HTTPS, email, SMS).",
    useCases: ["Fan-out alerts", "Mobile push notifications"],
    keyFeatures: ["FIFO topics", "Message filtering"],
    examTips: [
      "SNS = push, SQS = pull.",
      "Common pattern: SNS → multiple SQS queues (fan-out).",
    ],
  },
  {
    id: "eventbridge",
    name: "EventBridge",
    category: "Messaging & Integration",
    code: "EB",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Serverless event bus (successor to CloudWatch Events).",
    useCases: ["Event-driven architectures", "SaaS event routing"],
    keyFeatures: ["Default / custom / partner buses", "Schema Registry"],
    examTips: [
      "Routing events between AWS + SaaS (Datadog, Zendesk, Shopify) → EventBridge.",
      "More flexible than SNS for complex routing.",
    ],
  },
  {
    id: "amazon-mq",
    name: "Amazon MQ",
    category: "Messaging & Integration",
    code: "MQ",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Managed Apache ActiveMQ / RabbitMQ.",
    useCases: ["Migrate existing JMS/AMQP apps"],
    keyFeatures: ["Open-standard protocols"],
    examTips: ["Existing JMS/AMQP/MQTT app → Amazon MQ. Greenfield → SQS/SNS."],
  },

  // ────────── Analytics ──────────
  {
    id: "athena",
    name: "Athena",
    category: "Analytics",
    code: "ATH",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Serverless SQL queries over S3.",
    useCases: ["Ad-hoc S3 analytics", "Logs analysis"],
    keyFeatures: ["Presto under the hood", "Pay per TB scanned"],
    examTips: [
      "Query S3 with SQL, no servers → Athena.",
      "Partition your S3 data + columnar (Parquet) to save money.",
    ],
  },
  {
    id: "glue",
    name: "Glue",
    category: "Analytics",
    code: "GL",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Serverless ETL + Data Catalog.",
    useCases: ["Schema discovery (crawlers)", "Spark-based ETL jobs"],
    keyFeatures: ["Data Catalog is shared with Athena, EMR, Redshift"],
    examTips: ["Managed ETL / serverless Spark → Glue."],
  },
  {
    id: "kinesis",
    name: "Kinesis",
    category: "Analytics",
    code: "KIN",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Real-time streaming: Data Streams, Firehose, Data Analytics, Video Streams.",
    useCases: ["Real-time ingestion", "Log streaming", "Click-stream analytics"],
    keyFeatures: [
      "Data Streams = low-latency (<1s), manual shards",
      "Firehose = near-real-time to S3/Redshift/OpenSearch, managed",
      "Data Analytics = SQL on streams (now Managed Service for Apache Flink)",
    ],
    examTips: [
      "Streaming to S3 with no code → Firehose.",
      "Sub-second custom processing → Data Streams.",
    ],
  },
  {
    id: "emr",
    name: "EMR",
    shortName: "Elastic MapReduce",
    category: "Analytics",
    code: "EMR",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Managed Hadoop / Spark / Hive / Presto clusters.",
    useCases: ["Big data processing", "Lift-and-shift Hadoop"],
    keyFeatures: ["Spot-friendly", "Integrates with S3, Glue Catalog"],
    examTips: ["Existing Hadoop/Spark → EMR."],
  },
  {
    id: "quicksight",
    name: "QuickSight",
    category: "Analytics",
    code: "QS",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Serverless BI and dashboards.",
    useCases: ["Dashboards on Redshift/Athena/RDS/S3"],
    keyFeatures: ["SPICE in-memory engine", "Pay-per-session pricing"],
    examTips: ["AWS-native BI tool → QuickSight."],
  },
  {
    id: "opensearch",
    name: "OpenSearch Service",
    category: "Analytics",
    code: "OS",
    color: "#8C4FFF",
    bgColor: "#f3e8fd",
    description: "Managed Elasticsearch / OpenSearch.",
    useCases: ["Log analytics", "Full-text search"],
    keyFeatures: ["Kibana/OpenSearch Dashboards"],
    examTips: ["Search + log analytics → OpenSearch."],
  },

  // ────────── AI / ML ──────────
  {
    id: "sagemaker",
    name: "SageMaker",
    category: "AI / ML",
    code: "SM",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "End-to-end ML platform: build, train, deploy.",
    useCases: ["Custom ML training", "Model deployment endpoints"],
    keyFeatures: ["Notebooks, Training Jobs, Endpoints", "SageMaker Canvas (no-code)"],
    examTips: ["Full ML lifecycle on AWS → SageMaker."],
  },
  {
    id: "rekognition",
    name: "Rekognition",
    category: "AI / ML",
    code: "RK",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "Image + video analysis: faces, objects, celebrities, moderation.",
    useCases: ["Content moderation", "Face search"],
    keyFeatures: ["Pretrained models"],
    examTips: ["Image / video analysis → Rekognition."],
  },
  {
    id: "comprehend",
    name: "Comprehend",
    category: "AI / ML",
    code: "CMP",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "NLP: entity recognition, sentiment, language detection.",
    useCases: ["Text analytics"],
    keyFeatures: ["Comprehend Medical for PHI extraction"],
    examTips: ["Text / sentiment → Comprehend."],
  },
  {
    id: "polly",
    name: "Polly",
    category: "AI / ML",
    code: "PL",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "Text-to-speech.",
    useCases: ["Voicing apps"],
    keyFeatures: ["Neural TTS voices"],
    examTips: ["Text → speech → Polly."],
  },
  {
    id: "transcribe",
    name: "Transcribe",
    category: "AI / ML",
    code: "TR",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "Speech-to-text.",
    useCases: ["Call center transcription"],
    keyFeatures: ["Speaker diarization"],
    examTips: ["Audio → text → Transcribe."],
  },
  {
    id: "translate",
    name: "Translate",
    category: "AI / ML",
    code: "TRL",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "Neural machine translation.",
    useCases: ["Localize content"],
    keyFeatures: ["75+ languages"],
    examTips: ["Language translation → Translate."],
  },
  {
    id: "lex",
    name: "Lex",
    category: "AI / ML",
    code: "LX",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "Build conversational bots (same tech as Alexa).",
    useCases: ["Chatbots", "IVR"],
    keyFeatures: ["ASR + NLU"],
    examTips: ["Build a chatbot → Lex."],
  },
  {
    id: "bedrock",
    name: "Bedrock",
    category: "AI / ML",
    code: "BR",
    color: "#01A88D",
    bgColor: "#e6f4ea",
    description: "Managed access to foundation models (Claude, Llama, Titan).",
    useCases: ["GenAI apps without managing infra"],
    keyFeatures: ["Model choice via single API", "Agents + Knowledge Bases"],
    examTips: ["Generative AI on AWS → Bedrock."],
  },

  // ────────── Management & Cost ──────────
  {
    id: "organizations",
    name: "Organizations",
    category: "Management & Cost",
    code: "ORG",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Multi-account management, consolidated billing, SCPs.",
    useCases: ["Central control of many AWS accounts"],
    keyFeatures: ["Service Control Policies (SCPs)", "Consolidated billing", "OUs"],
    examTips: [
      "SCPs = guardrails for what AWS services can be used in member accounts.",
      "Consolidated billing → volume discounts shared across accounts.",
      "SCPs do NOT grant permissions, they RESTRICT them.",
    ],
  },
  {
    id: "control-tower",
    name: "Control Tower",
    category: "Management & Cost",
    code: "CTW",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Easy landing-zone setup with best-practice guardrails.",
    useCases: ["Well-architected multi-account setup"],
    keyFeatures: ["Account Factory (provisioning)"],
    examTips: ["Multi-account 'landing zone' → Control Tower."],
  },
  {
    id: "cost-explorer",
    name: "Cost Explorer",
    category: "Management & Cost",
    code: "CE",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Visualize, analyze, and forecast AWS costs.",
    useCases: ["Cost allocation", "Rightsizing recommendations"],
    keyFeatures: ["Savings Plans recommendations"],
    examTips: ["Analyze past + forecast future costs → Cost Explorer."],
  },
  {
    id: "budgets",
    name: "AWS Budgets",
    category: "Management & Cost",
    code: "BD",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Budget alerts on cost/usage thresholds.",
    useCases: ["Alert on spend overruns"],
    keyFeatures: ["Cost / usage / RI utilization / Savings Plan budgets"],
    examTips: [
      "Alerts only — Budgets does not stop services automatically.",
      "AWS Budgets Actions CAN automate responses (stop EC2, attach deny SCP).",
    ],
  },
  {
    id: "cost-and-usage-report",
    name: "Cost & Usage Report",
    shortName: "CUR",
    category: "Management & Cost",
    code: "CUR",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Detailed hourly cost data delivered to S3.",
    useCases: ["Detailed chargeback / showback"],
    keyFeatures: ["Hourly granularity"],
    examTips: ["Most granular billing data → CUR (delivered to S3)."],
  },
  {
    id: "pricing-calculator",
    name: "Pricing Calculator",
    category: "Management & Cost",
    code: "PC",
    color: "#E7157B",
    bgColor: "#fce8e6",
    description: "Estimate cost of AWS architectures before building.",
    useCases: ["Pre-build cost estimates"],
    keyFeatures: ["Replaces Simple Monthly Calculator"],
    examTips: ["Estimate AWS cost before deploying → Pricing Calculator."],
  },

  // ────────── Support ──────────
  {
    id: "support-plans",
    name: "Support Plans",
    category: "Support",
    code: "SUP",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Basic, Developer, Business, Enterprise On-Ramp, Enterprise.",
    useCases: ["Different levels of AWS support"],
    keyFeatures: [
      "Basic (free)",
      "Developer (email, biz hours)",
      "Business (24/7 phone/chat, <1h response for prod down)",
      "Enterprise ($15K/mo, TAM, <15 min critical)",
    ],
    examTips: [
      "TAM (Technical Account Manager) = Enterprise & Enterprise On-Ramp only.",
      "Business + is required for full Trusted Advisor + API access.",
      "Know response times: prod-down = 1 h (Business) vs 15 min (Enterprise).",
    ],
  },
  {
    id: "professional-services",
    name: "Professional Services & Partners",
    category: "Support",
    code: "PS",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "AWS consulting + APN (AWS Partner Network).",
    useCases: ["Hands-on migration help", "Finding partners via AWS Marketplace"],
    keyFeatures: ["Consulting Partners", "Technology Partners"],
    examTips: ["Need hands-on help → Professional Services or APN partner."],
  },
  {
    id: "marketplace",
    name: "AWS Marketplace",
    category: "Support",
    code: "MKT",
    color: "#DD344C",
    bgColor: "#fce8e6",
    description: "Digital catalog to buy / subscribe to 3rd-party software that runs on AWS.",
    useCases: ["Buy pre-configured AMIs / SaaS"],
    keyFeatures: ["Single invoice via AWS"],
    examTips: ["Buy 3rd-party software that billed via AWS → Marketplace."],
  },
];
