export interface CloudService {
  id: string;
  name: string;
  shortName?: string;
  category: string;
  code: string;
  color: string;
  bgColor: string;
  description: string;
  useCases: string[];
  keyFeatures: string[];
  examTips: string[];
}

// Categories in the order they'll appear in the grid
export const gcpCategories = [
  "Compute",
  "Containers",
  "Serverless",
  "Storage",
  "Databases",
  "Networking",
  "Security & IAM",
  "Operations",
  "DevOps",
  "Data & Analytics",
  "AI / ML",
  "Management",
];

export const gcpServices: CloudService[] = [
  // ────────── Compute ──────────
  {
    id: "compute-engine",
    name: "Compute Engine",
    shortName: "GCE",
    category: "Compute",
    code: "CE",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description:
      "Virtual machines running on Google's infrastructure. IaaS offering with highly configurable CPU, memory, GPU and disk.",
    useCases: [
      "Lift-and-shift workloads from on-premise",
      "Custom OS / kernel requirements",
      "Long-running stateful services",
      "GPU workloads (ML training, rendering)",
    ],
    keyFeatures: [
      "Machine types: General-purpose (E2/N2/N1), Compute-optimized (C2), Memory-optimized (M2)",
      "Preemptible / Spot VMs — up to 91% cheaper, 24h max runtime",
      "Sustained-use and committed-use discounts",
      "Live migration during maintenance",
    ],
    examTips: [
      "Preemptible VMs are the cheapest but can be terminated at any time → use for fault-tolerant batch jobs.",
      "Committed-use discounts = 1 or 3 years — best for steady, predictable workloads.",
      "Sustained-use discounts apply automatically (no action needed).",
      "Use instance templates + managed instance groups (MIGs) for autoscaling.",
    ],
  },
  {
    id: "instance-groups",
    name: "Managed Instance Groups",
    shortName: "MIG",
    category: "Compute",
    code: "MIG",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description:
      "Auto-healing, auto-scaling groups of identical VMs created from an instance template.",
    useCases: [
      "Stateless web servers behind a load balancer",
      "Auto-scale based on CPU, HTTP load, or custom metrics",
      "Rolling updates and canary deployments",
    ],
    keyFeatures: [
      "Regional (multi-zone) or Zonal",
      "Auto-healing via health checks",
      "Rolling updates with max surge/unavailable",
    ],
    examTips: [
      "Regional MIGs give higher availability than zonal MIGs — pick them for production.",
      "Stateful MIGs preserve disk + metadata per VM — use for legacy apps needing identity.",
      "Instance template is immutable — edit = create new template and update the MIG.",
    ],
  },
  {
    id: "bare-metal",
    name: "Bare Metal Solution",
    category: "Compute",
    code: "BM",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Dedicated hardware in a Google-managed colocation — ideal for Oracle workloads.",
    useCases: ["Oracle databases", "Specialized hardware-licensed software"],
    keyFeatures: ["Low-latency to GCP services", "Physical isolation"],
    examTips: ["When you see 'Oracle workloads' + GCP → Bare Metal Solution."],
  },

  // ────────── Containers ──────────
  {
    id: "gke",
    name: "Google Kubernetes Engine",
    shortName: "GKE",
    category: "Containers",
    code: "GKE",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed Kubernetes clusters. Autopilot (fully managed) or Standard mode.",
    useCases: [
      "Microservices and containerized workloads",
      "Hybrid/multi-cloud via Anthos",
      "Replatforming existing containers",
    ],
    keyFeatures: [
      "Autopilot: pay per pod, Google manages nodes",
      "Standard: you manage node pools",
      "Regional clusters for high availability",
      "Workload Identity for secure access to GCP APIs",
    ],
    examTips: [
      "Autopilot removes node management — best for users who don't want to tune nodes.",
      "Use Workload Identity — NEVER use node service-account keys for pod-level auth.",
      "Regional cluster > Zonal cluster for production HA.",
      "kubectl auth is obtained via `gcloud container clusters get-credentials`.",
    ],
  },
  {
    id: "artifact-registry",
    name: "Artifact Registry",
    shortName: "AR",
    category: "Containers",
    code: "AR",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description:
      "Universal package manager for Docker, Maven, npm, Python, Helm etc. Successor to Container Registry.",
    useCases: ["Store container images", "Host language-specific packages"],
    keyFeatures: ["Regional or multi-regional repos", "Vulnerability scanning", "IAM-based access"],
    examTips: [
      "Prefer Artifact Registry over Container Registry — CR is deprecated.",
      "Integrates with Binary Authorization for trusted deploys to GKE.",
    ],
  },

  // ────────── Serverless ──────────
  {
    id: "cloud-run",
    name: "Cloud Run",
    category: "Serverless",
    code: "CR",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Fully managed container runtime. Any language, scales to zero, pay per request.",
    useCases: [
      "HTTP APIs and web apps",
      "Event-driven services",
      "Stateless microservices",
    ],
    keyFeatures: [
      "Scale to zero",
      "Custom domains, HTTPS by default",
      "Up to 60 min request timeout (v2)",
      "CPU always allocated option for background tasks",
    ],
    examTips: [
      "Scales to zero — cheapest for low-traffic HTTP workloads.",
      "Cloud Run (services) = HTTP; Cloud Run jobs = batch / one-shot tasks.",
      "If container image + HTTP → Cloud Run; if source only → App Engine or Cloud Functions.",
    ],
  },
  {
    id: "cloud-functions",
    name: "Cloud Functions",
    shortName: "CF",
    category: "Serverless",
    code: "CF",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Event-driven functions. Responds to HTTP or Pub/Sub / Storage / Firestore events.",
    useCases: ["Glue code between services", "Webhooks", "Lightweight APIs"],
    keyFeatures: ["Gen 2 runs on Cloud Run under the hood", "9 min HTTP timeout (Gen 1), 60 min (Gen 2)"],
    examTips: [
      "Trigger-based workloads → Cloud Functions.",
      "Gen 2 is the modern choice — longer timeouts, larger instances.",
    ],
  },
  {
    id: "app-engine",
    name: "App Engine",
    shortName: "GAE",
    category: "Serverless",
    code: "AE",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "PaaS for web apps. Standard (sandboxed runtimes) or Flexible (Docker).",
    useCases: ["Monolithic web apps", "Traffic splitting / A-B testing", "Legacy Standard apps"],
    keyFeatures: ["Traffic splitting by version", "Zero-server management", "Automatic scaling"],
    examTips: [
      "App Engine Standard scales to zero; Flex does NOT (min 1 instance).",
      "Use traffic splitting for gradual rollouts.",
      "Only ONE App Engine app per project — region is fixed at creation.",
    ],
  },
  {
    id: "cloud-workflows",
    name: "Workflows",
    category: "Serverless",
    code: "WF",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Orchestrate services in a declarative YAML/JSON workflow.",
    useCases: ["Chaining Cloud Functions / Cloud Run", "Serverless orchestration"],
    keyFeatures: ["Built-in retries, error handling", "Pay per step executed"],
    examTips: ["When you need to orchestrate multiple serverless calls → Workflows."],
  },

  // ────────── Storage ──────────
  {
    id: "cloud-storage",
    name: "Cloud Storage",
    shortName: "GCS",
    category: "Storage",
    code: "GCS",
    color: "#34A853",
    bgColor: "#e6f4ea",
    description: "Object storage. Global namespace, strong consistency.",
    useCases: [
      "Static websites",
      "Data lake",
      "Backups / archives",
      "ML training data",
    ],
    keyFeatures: [
      "Classes: Standard, Nearline (30d), Coldline (90d), Archive (365d)",
      "Location: regional, dual-region, multi-region",
      "Object Lifecycle Management",
      "Versioning, retention policies, object holds",
    ],
    examTips: [
      "Nearline = accessed <1x/month. Coldline = <1x/quarter. Archive = <1x/year.",
      "Use lifecycle rules to auto-transition objects to cheaper classes.",
      "Signed URLs give time-limited access WITHOUT IAM permissions.",
      "Uniform bucket-level access disables per-object ACLs — recommended.",
    ],
  },
  {
    id: "persistent-disk",
    name: "Persistent Disk",
    shortName: "PD",
    category: "Storage",
    code: "PD",
    color: "#34A853",
    bgColor: "#e6f4ea",
    description: "Block storage for Compute Engine VMs.",
    useCases: ["VM boot disks", "Databases running on VMs"],
    keyFeatures: ["Standard (HDD), Balanced, SSD, Extreme SSD", "Regional PD replicates across 2 zones"],
    examTips: [
      "Regional PD survives a zone failure — use for HA workloads.",
      "Snapshots are incremental and global (usable in any region).",
    ],
  },
  {
    id: "filestore",
    name: "Filestore",
    category: "Storage",
    code: "FS",
    color: "#34A853",
    bgColor: "#e6f4ea",
    description: "Managed NFS file storage.",
    useCases: ["Shared file systems for VMs", "Lift-and-shift NFS apps"],
    keyFeatures: ["Basic, Zonal, Enterprise tiers"],
    examTips: ["NFS / shared filesystem requirement → Filestore."],
  },

  // ────────── Databases ──────────
  {
    id: "cloud-sql",
    name: "Cloud SQL",
    category: "Databases",
    code: "SQL",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed MySQL, PostgreSQL, SQL Server. Single-region, scales vertically.",
    useCases: ["Traditional relational apps", "Regional OLTP"],
    keyFeatures: ["Automated backups, HA with failover replica", "Read replicas", "Private IP via VPC peering"],
    examTips: [
      "Cloud SQL = regional; for GLOBAL / horizontal scale → Spanner.",
      "HA configuration uses a standby in another zone — automatic failover.",
      "Use Cloud SQL Auth Proxy for secure connections without whitelisting IPs.",
    ],
  },
  {
    id: "spanner",
    name: "Cloud Spanner",
    category: "Databases",
    code: "SP",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Globally distributed, strongly consistent relational DB. Horizontally scalable.",
    useCases: ["Global financial systems", "Mission-critical high-scale OLTP"],
    keyFeatures: ["99.999% SLA (multi-region)", "SQL + strong consistency at global scale"],
    examTips: [
      "Global + relational + horizontal scale → Spanner.",
      "Most expensive DB — use only when scale demands it.",
    ],
  },
  {
    id: "bigtable",
    name: "Bigtable",
    category: "Databases",
    code: "BT",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Petabyte-scale NoSQL wide-column store. Low-latency, high-throughput.",
    useCases: ["Time-series data (IoT, finance)", "Analytical workloads", "Ad tech"],
    keyFeatures: ["HBase-compatible API", "Millisecond reads/writes", "Scales to billions of rows"],
    examTips: [
      "IoT / time-series / analytical workloads → Bigtable.",
      "Min cluster = 1 node; plan schema around row keys (hotspots kill performance).",
      "Not SQL; use HBase API.",
    ],
  },
  {
    id: "firestore",
    name: "Firestore",
    category: "Databases",
    code: "FI",
    color: "#FFA000",
    bgColor: "#fff3e0",
    description: "Serverless NoSQL document database. Real-time sync.",
    useCases: ["Mobile / web apps with offline sync", "Hierarchical data"],
    keyFeatures: ["Real-time listeners", "ACID transactions", "Native + Datastore mode"],
    examTips: [
      "Mobile/web apps with real-time sync → Firestore.",
      "Datastore mode = backward-compatible with App Engine Datastore.",
    ],
  },
  {
    id: "memorystore",
    name: "Memorystore",
    category: "Databases",
    code: "MS",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Managed Redis and Memcached.",
    useCases: ["Caching layer", "Session storage", "Leaderboards"],
    keyFeatures: ["Redis or Memcached", "HA with automatic failover"],
    examTips: ["In-memory cache → Memorystore. Redis > Memcached for persistence + data structures."],
  },
  {
    id: "bigquery",
    name: "BigQuery",
    shortName: "BQ",
    category: "Databases",
    code: "BQ",
    color: "#669DF6",
    bgColor: "#e8f0fe",
    description: "Serverless data warehouse. SQL analytics at petabyte scale.",
    useCases: ["Data warehousing", "Ad-hoc analytics", "BI dashboards"],
    keyFeatures: ["Pay per query (on-demand) or flat-rate", "Separation of storage and compute", "ML built-in (BQML)"],
    examTips: [
      "Data warehouse + SQL analytics → BigQuery.",
      "Partitioning + clustering = query cost control.",
      "BQ Omni = query data in AWS S3 / Azure Blob from BigQuery.",
    ],
  },

  // ────────── Networking ──────────
  {
    id: "vpc",
    name: "VPC",
    category: "Networking",
    code: "VPC",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Virtual Private Cloud — global, software-defined network.",
    useCases: ["Network isolation", "Hybrid connectivity backbone"],
    keyFeatures: [
      "GLOBAL resource — subnets are regional",
      "Shared VPC for org-wide network",
      "VPC Peering (non-transitive)",
    ],
    examTips: [
      "VPC is GLOBAL; subnets are REGIONAL. Common exam trap.",
      "Shared VPC = centralize network admin at the org level (host project + service projects).",
      "VPC Peering is non-transitive — use VPN/Interconnect or Network Connectivity Center for hub-and-spoke.",
    ],
  },
  {
    id: "cloud-lb",
    name: "Cloud Load Balancing",
    shortName: "CLB",
    category: "Networking",
    code: "LB",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Global / regional L4 & L7 load balancers using a single anycast IP.",
    useCases: ["Global web apps", "TCP/UDP load balancing", "Internal load balancing"],
    keyFeatures: [
      "Global HTTPS LB with 1 anycast IP",
      "TCP/SSL Proxy, Network LB, Internal LB",
      "Integrates with Cloud CDN, Cloud Armor",
    ],
    examTips: [
      "Global anycast IP with HTTP(S) → Global External HTTPS LB.",
      "Internal traffic only → Internal LB.",
      "Preserving client source IP → Network LB (passthrough).",
    ],
  },
  {
    id: "cloud-cdn",
    name: "Cloud CDN",
    category: "Networking",
    code: "CDN",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Global content delivery network on Google's edge POPs.",
    useCases: ["Static content caching", "Accelerating dynamic content"],
    keyFeatures: ["Works with HTTPS LB only", "Cache invalidation APIs"],
    examTips: ["Cloud CDN requires a Global HTTPS LB as its origin."],
  },
  {
    id: "cloud-armor",
    name: "Cloud Armor",
    category: "Networking",
    code: "CA",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "DDoS protection + WAF for Google Cloud services.",
    useCases: ["Protect internet-facing apps from DDoS/SQLi/XSS"],
    keyFeatures: ["Attached to backend services of HTTPS LB", "Managed rules (OWASP top 10)"],
    examTips: ["Web application firewall / DDoS → Cloud Armor at the LB."],
  },
  {
    id: "cloud-dns",
    name: "Cloud DNS",
    category: "Networking",
    code: "DNS",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Scalable, 100% uptime SLA, authoritative DNS.",
    useCases: ["Public or private DNS zones"],
    keyFeatures: ["DNSSEC", "Private zones resolvable inside a VPC"],
    examTips: ["Private DNS zones are only resolvable from the associated VPC."],
  },
  {
    id: "interconnect",
    name: "Cloud Interconnect",
    category: "Networking",
    code: "IC",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Dedicated physical (or partner) connection to GCP.",
    useCases: ["Low-latency, high-throughput on-prem ↔ GCP"],
    keyFeatures: ["Dedicated: 10 / 100 Gbps", "Partner: 50 Mbps – 50 Gbps"],
    examTips: [
      "Dedicated Interconnect needs a POP colocation facility.",
      "Partner Interconnect = go via a partner ISP (more flexible, less throughput).",
      "For encrypted / lower bandwidth → Cloud VPN.",
    ],
  },
  {
    id: "cloud-vpn",
    name: "Cloud VPN",
    category: "Networking",
    code: "VPN",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "IPsec VPN to on-premise over the public internet.",
    useCases: ["Encrypted hybrid connectivity", "Lower bandwidth on-prem links"],
    keyFeatures: ["Classic VPN or HA VPN (99.99% SLA)"],
    examTips: ["Always pick HA VPN over Classic for production."],
  },
  {
    id: "cloud-nat",
    name: "Cloud NAT",
    category: "Networking",
    code: "NAT",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed NAT for VMs without external IPs.",
    useCases: ["Private VMs reaching the internet for updates/APIs"],
    keyFeatures: ["No managed NAT instances", "Per-region service"],
    examTips: ["Private VMs need internet egress → Cloud NAT (no public IPs required)."],
  },

  // ────────── Security & IAM ──────────
  {
    id: "iam",
    name: "Cloud IAM",
    category: "Security & IAM",
    code: "IAM",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Fine-grained access control. Identities → Roles → Resources.",
    useCases: ["Least-privilege access", "Service-to-service authentication"],
    keyFeatures: ["Predefined, Basic, and Custom roles", "Conditions (IAM Conditions)"],
    examTips: [
      "Prefer predefined roles over Basic (Owner/Editor/Viewer) — too permissive.",
      "Use Service Accounts for workloads — NEVER share user credentials.",
      "IAM is hierarchical: Org → Folder → Project → Resource. Policies inherit downward.",
    ],
  },
  {
    id: "service-accounts",
    name: "Service Accounts",
    shortName: "SA",
    category: "Security & IAM",
    code: "SA",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Non-human identity used by VMs, services and apps to call APIs.",
    useCases: ["Compute Engine VM → GCS access", "Cloud Run → BigQuery"],
    keyFeatures: ["Attached to a resource", "Workload Identity for GKE"],
    examTips: [
      "Prefer Workload Identity (GKE) over mounting SA keys.",
      "Downloaded SA keys are a security risk — rotate and avoid where possible.",
    ],
  },
  {
    id: "kms",
    name: "Cloud KMS",
    category: "Security & IAM",
    code: "KMS",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Managed cryptographic key service.",
    useCases: ["Encrypt data at rest with CMEK", "Rotating keys"],
    keyFeatures: ["Software, HSM, External (EKM)", "Automatic key rotation"],
    examTips: [
      "CMEK (Customer-Managed) = keys in KMS; CSEK = Customer-Supplied (you provide raw key).",
      "EKM = key stays in external HSM (partner).",
    ],
  },
  {
    id: "secret-manager",
    name: "Secret Manager",
    shortName: "SM",
    category: "Security & IAM",
    code: "SM",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Store API keys, passwords, certificates.",
    useCases: ["App secrets", "Credential rotation"],
    keyFeatures: ["Versioning, replication policy", "IAM-gated access"],
    examTips: ["Secrets in code / env vars → replace with Secret Manager."],
  },
  {
    id: "scc",
    name: "Security Command Center",
    shortName: "SCC",
    category: "Security & IAM",
    code: "SCC",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Central security and risk dashboard for the org.",
    useCases: ["Vulnerability scanning", "Misconfiguration detection", "Threat detection"],
    keyFeatures: ["Standard (free) and Premium tiers"],
    examTips: ["Central security posture for the organization → Security Command Center."],
  },
  {
    id: "vpc-sc",
    name: "VPC Service Controls",
    category: "Security & IAM",
    code: "SC",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Data-exfiltration perimeter around GCP services.",
    useCases: ["Prevent public access to BigQuery/GCS from outside the perimeter"],
    keyFeatures: ["Service perimeters", "Access levels"],
    examTips: ["Prevent data exfiltration from services like BQ/GCS → VPC Service Controls."],
  },

  // ────────── Operations ──────────
  {
    id: "cloud-logging",
    name: "Cloud Logging",
    category: "Operations",
    code: "LOG",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Centralized logging for all GCP + custom app logs.",
    useCases: ["Aggregate logs", "Log-based metrics", "Export to BQ/Storage/Pub/Sub"],
    keyFeatures: ["Log sinks", "Log Router", "Retention up to 10 years"],
    examTips: [
      "Export logs to BigQuery for analytics, GCS for archive, Pub/Sub for streaming.",
      "Log-based metrics turn log patterns into monitored metrics.",
    ],
  },
  {
    id: "cloud-monitoring",
    name: "Cloud Monitoring",
    category: "Operations",
    code: "MON",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Metrics, dashboards, and alerts.",
    useCases: ["Uptime checks", "SLO monitoring", "Alerting"],
    keyFeatures: ["Workspaces (scoping projects)", "Uptime checks", "Alert policies"],
    examTips: ["Uptime checks + alerting are free tier features."],
  },
  {
    id: "cloud-trace",
    name: "Cloud Trace",
    category: "Operations",
    code: "TR",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Distributed tracing to find latency bottlenecks.",
    useCases: ["Microservices latency analysis"],
    keyFeatures: ["Auto-collection in App Engine / Cloud Run / GKE with OpenTelemetry"],
    examTips: ["Latency issue across services → Cloud Trace."],
  },
  {
    id: "error-reporting",
    name: "Error Reporting",
    category: "Operations",
    code: "ER",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Aggregates exceptions from apps into unique groups.",
    useCases: ["Crash monitoring"],
    keyFeatures: ["Deduplicates errors", "Real-time alerts"],
    examTips: ["Stack-trace/exception aggregation → Error Reporting."],
  },

  // ────────── DevOps ──────────
  {
    id: "cloud-build",
    name: "Cloud Build",
    category: "DevOps",
    code: "CB",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Serverless CI/CD platform.",
    useCases: ["Build container images", "Run tests", "Deploy to GKE / Cloud Run"],
    keyFeatures: ["Triggered by Git push / PR", "120 build-min/day free"],
    examTips: ["GCP-native CI/CD → Cloud Build. Alternative: GitHub Actions."],
  },
  {
    id: "cloud-deploy",
    name: "Cloud Deploy",
    category: "DevOps",
    code: "CD",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed continuous delivery to GKE / Cloud Run / Anthos.",
    useCases: ["Promote releases across dev → staging → prod"],
    keyFeatures: ["Skaffold-based pipelines", "Audit trail of promotions"],
    examTips: ["Progressive delivery pipeline to GKE → Cloud Deploy."],
  },
  {
    id: "source-repos",
    name: "Source Repositories",
    category: "DevOps",
    code: "SR",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Private Git repos inside GCP.",
    useCases: ["Mirror GitHub", "Git-based source for Cloud Build"],
    keyFeatures: ["Integrates with Cloud Debugger / Build"],
    examTips: ["Usually replaced by GitHub; know it exists."],
  },

  // ────────── Data & Analytics ──────────
  {
    id: "pubsub",
    name: "Pub/Sub",
    category: "Data & Analytics",
    code: "PS",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Global messaging service. At-least-once delivery.",
    useCases: ["Event-driven architectures", "Streaming ingestion", "Decoupling services"],
    keyFeatures: ["Push and Pull subscriptions", "Dead-letter topics", "Ordering keys"],
    examTips: [
      "Global, at-least-once, asynchronous → Pub/Sub.",
      "Pair with Dataflow for stream processing.",
    ],
  },
  {
    id: "dataflow",
    name: "Dataflow",
    category: "Data & Analytics",
    code: "DF",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed Apache Beam — batch + streaming pipelines.",
    useCases: ["ETL", "Real-time analytics", "Stream processing from Pub/Sub to BigQuery"],
    keyFeatures: ["Unified batch + stream", "Autoscaling", "Templates (Pub/Sub to BQ etc.)"],
    examTips: [
      "Batch + stream from the same codebase → Dataflow.",
      "Reference pipeline: Pub/Sub → Dataflow → BigQuery.",
    ],
  },
  {
    id: "dataproc",
    name: "Dataproc",
    category: "Data & Analytics",
    code: "DP",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed Hadoop / Spark clusters.",
    useCases: ["Lift-and-shift existing Hadoop jobs"],
    keyFeatures: ["Ephemeral clusters", "Autoscaling"],
    examTips: ["Existing Hadoop/Spark workload → Dataproc (not Dataflow)."],
  },
  {
    id: "composer",
    name: "Cloud Composer",
    category: "Data & Analytics",
    code: "CO",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Managed Apache Airflow.",
    useCases: ["Orchestrating ETL DAGs", "Cross-cloud pipelines"],
    keyFeatures: ["Python-defined DAGs"],
    examTips: ["Airflow-based orchestration → Cloud Composer."],
  },
  {
    id: "datafusion",
    name: "Data Fusion",
    category: "Data & Analytics",
    code: "DFU",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Visual, no-code ETL on top of Cloud Data Fusion (CDAP).",
    useCases: ["Codeless data pipelines"],
    keyFeatures: ["150+ connectors"],
    examTips: ["Visual ETL without code → Data Fusion."],
  },

  // ────────── AI / ML ──────────
  {
    id: "vertex-ai",
    name: "Vertex AI",
    category: "AI / ML",
    code: "VX",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Unified ML platform — training, deployment, AutoML, Gemini models.",
    useCases: ["Custom ML", "AutoML", "Gemini API"],
    keyFeatures: ["Workbench, Pipelines, Model Registry, Endpoints"],
    examTips: ["Single-pane ML platform → Vertex AI (successor to AI Platform)."],
  },
  {
    id: "ai-apis",
    name: "Pretrained AI APIs",
    category: "AI / ML",
    code: "API",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Vision, Speech-to-Text, Translation, NLP, Document AI.",
    useCases: ["Plug-and-play AI without training"],
    keyFeatures: ["REST APIs"],
    examTips: ["Off-the-shelf ML task (image, speech, text) → Pretrained API first, not custom model."],
  },

  // ────────── Management ──────────
  {
    id: "resource-manager",
    name: "Resource Manager",
    category: "Management",
    code: "RM",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Hierarchy of Organizations → Folders → Projects.",
    useCases: ["Apply IAM / policies at scale"],
    keyFeatures: ["Folders to group projects", "Labels for filtering"],
    examTips: [
      "Policies on parent nodes are inherited by children.",
      "Use Folders to mirror org structure (dept, env, team).",
    ],
  },
  {
    id: "org-policy",
    name: "Organization Policy",
    category: "Management",
    code: "OP",
    color: "#EA4335",
    bgColor: "#fce8e6",
    description: "Guardrails that constrain GCP resource configuration org-wide.",
    useCases: ["Restrict VM external IPs", "Enforce resource locations"],
    keyFeatures: ["Boolean + List constraints"],
    examTips: [
      "Org Policy is ABOUT the resource (what you can configure), IAM is about WHO can do it.",
    ],
  },
  {
    id: "billing",
    name: "Cloud Billing",
    category: "Management",
    code: "BIL",
    color: "#34A853",
    bgColor: "#e6f4ea",
    description: "Billing accounts, budgets and cost exports.",
    useCases: ["Budget alerts", "Cost export to BigQuery"],
    keyFeatures: ["Master + sub-accounts", "Budgets with threshold alerts (no auto-stop)"],
    examTips: [
      "Budget alerts NOTIFY — they do not cap spend. Use Pub/Sub + function to take action.",
      "One billing account can fund multiple projects.",
    ],
  },
  {
    id: "deployment-manager",
    name: "Deployment Manager",
    category: "Management",
    code: "DM",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "GCP-native IaC (YAML + Jinja / Python).",
    useCases: ["Template-based provisioning"],
    keyFeatures: ["Declarative templates"],
    examTips: ["Terraform is generally preferred for multi-cloud; DM is GCP-only."],
  },
  {
    id: "cloud-scheduler",
    name: "Cloud Scheduler",
    category: "Management",
    code: "SCH",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Fully managed cron.",
    useCases: ["Scheduled Cloud Functions / Cloud Run invocations", "Periodic batch"],
    keyFeatures: ["HTTP, Pub/Sub, App Engine targets"],
    examTips: ["Cron-style trigger → Cloud Scheduler (not Workflows)."],
  },
  {
    id: "cloud-tasks",
    name: "Cloud Tasks",
    category: "Management",
    code: "TSK",
    color: "#4285F4",
    bgColor: "#e8f0fe",
    description: "Asynchronous task queues with rate + retry control.",
    useCases: ["Decouple user requests from background work"],
    keyFeatures: ["Per-queue rate limits", "Retries with backoff"],
    examTips: [
      "Pub/Sub = pub-sub fan-out (topic → many subscribers).",
      "Cloud Tasks = targeted queue (one worker per task with retry policies).",
    ],
  },
];
